version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/Minigames"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/Regions"
    schedule:
      interval: "weekly"
