saveInventory: true
requireEmptyInventory: false
forceload: false
debug: false
pasteApiKey:

treasurehunt:
  waittime: 3600
  # Time to wait before spawning a new treasure after the time was up (seconds)

multiplayer:
  waitforplayers: 10
  # Time to wait for players before starting
  startcountdown: 5
  # Time before game actually starts
  timerMessageInterval:
    - 900
    - 600
    - 300
    - 60
    - 30
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1
  floordegenerator:
    time: 30
  ctf:
    flagrespawntime: 60

disabledCommands:
  - home
  - warp
  - spawn
  
broadcastCompletion: true
playSounds: true
  
regeneration:
  maxDelay: 10
  
updateChecker: false
# Whether the plugin should check for updates

lang: 'en_AU'
# Select language
  
backend:
  # Can be sqlite, or mysql
  type: sqlite
  host: localhost:3306
  database: database
  username: username
  password: password
  properties:
    useSSL: false

tool: "BLAZE_ROD"

warnings: true

outputCMDToFile: false

minigames:
  {}