name: Minigames-Regions
main: au.com.mineauz.minigamesregions.Main
version: ${plugin.version}
api-version: ${spigot.api.version}
author: _Razz_ AddstarMC
depend: [ 'Minigames' ]
description: ${project.description}